#ifndef _SUSI_IMC_DISPLAY_API_H
#define _SUSI_IMC_DISPLAY_API_H

#include "SUSI_IMC_Types.h"

DLLAPI USHORT SUSI_IMC_DISPLAY_GetLibVersion( OUT BYTE version[18] );
DLLAPI USHORT SUSI_IMC_DISPLAY_Available();
DLLAPI USHORT SUSI_IMC_DISPLAY_ScreenOn();
DLLAPI USHORT SUSI_IMC_DISPLAY_ScreenOff();
DLLAPI USHORT SUSI_IMC_DISPLAY_GetBrightRange(PIMC_DISPLAY_GET_BRIGHT_RANGE parm);
DLLAPI USHORT SUSI_IMC_DISPLAY_GetBright(BYTE *brightness);
DLLAPI USHORT SUSI_IMC_DISPLAY_SetBright(BYTE brightness);

#endif