
#ifndef _SUSI_IMC_BRIGHTNESS_API_H
#define _SUSI_IMC_BRIGHTNESS_API_H

#include "SUSI_IMC_Types.h"

DLLAPI USHORT SUSI_IMC_BRIGHTNESS_SetDutyCycle(IN BYTE level, IN BYTE duty_cycle );
DLLAPI USHORT SUSI_IMC_BRIGHTNESS_GetDutyCycle(IN BYTE level, OUT PBYTE duty_cycle );
DLLAPI USHORT SUSI_IMC_BRIGHTNESS_SetLevel(IN PIMC_BRIGHTNESS_LEVEL level );
DLLAPI USHORT SUSI_IMC_BRIGHTNESS_GetLevel ( OUT PIMC_BRIGHTNESS_LEVEL level );

typedef USHORT (*PSUSI_IMC_BRIGHTNESS_SetLevel)(PIMC_BRIGHTNESS_LEVEL level);
typedef USHORT (*PSUSI_IMC_BRIGHTNESS_GetLevel)(PIMC_BRIGHTNESS_LEVEL level);

#endif