
#ifndef _SUSI_IMC_CONTROLPANEL_API_H
#define _SUSI_IMC_CONTROLPANEL_API_H

#include "SUSI_IMC_Types.h"

DLLAPI USHORT SUSI_IMC_CONTROLPANEL_GetVersion ( OUT PBYTE version );
DLLAPI USHORT SUSI_IMC_CONTROLPANEL_Initialize ( IN BYTE port_number );
DLLAPI USHORT SUSI_IMC_CONTROLPANEL_Deinitialize ( void );
DLLAPI USHORT SUSI_IMC_CONTROLPANEL_GetFirmwareInformation ( OUT PIMC_CONTROLPANEL_FIRMWARE_INFO info );
DLLAPI USHORT SUSI_IMC_CONTROLPANEL_ResetFirmware ( IN BYTE mode );
DLLAPI USHORT SUSI_IMC_CONTROLPANEL_LoadDefaultValue ( void );
DLLAPI USHORT SUSI_IMC_CONTROLPANEL_TEMPERATURE_GetValue ( OUT float *val );

typedef USHORT (*PSUSI_IMC_CONTROLPANEL_Initialize)(BYTE port_number);
typedef USHORT (*PSUSI_IMC_CONTROLPANEL_Deinitialize)(void);

#endif