#ifndef _SUSI_IMC_J1708_API_H
#define _SUSI_IMC_J1708_API_H

DLLAPI USHORT SUSI_IMC_J1708_Read( OUT PIMC_J1708_MSG_OBJECT object );
DLLAPI USHORT SUSI_IMC_J1708_Write( IN PIMC_J1708_MSG_OBJECT object );
DLLAPI USHORT SUSI_IMC_J1708_SetEvent( void* hEvent );
DLLAPI USHORT SUSI_IMC_J1708_AddMessageFilter( IN UINT mid );
DLLAPI USHORT SUSI_IMC_J1708_GetMessageFilter( OUT UINT* total, OUT UINT* mid );
DLLAPI USHORT SUSI_IMC_J1708_RemoveMessageFilter( IN UINT mid );
DLLAPI USHORT SUSI_IMC_J1708_RemoveAllMessageFilter ( void );

#endif