#ifndef SUSI_PERIPHERALCTRL_DEF_H
#define SUSI_PERIPHERALCTRL_DEF_H

enum PERIPHERAL_TYPE
{
	PERIPHERAL_WWAN = 0,
	PERIPHERAL_WIFI = 1,
	PERIPHERAL_GPS = 2,
	PERIPHERAL_ALTIMETER = 3,
	PERIPHERAL_GSENSOR = 4,
	PERIPHERAL_GPS_USB = 5,
	PERIPHERAL_SPEAKER = 6,
	PERIPHERAL_SIM0 = 7,
	PERIPHERAL_SIM1 = 8,
	PERIPHERAL_CAN = 9,
	PERIPHERAL_SIZE
};

#define SUSI_REAR_VIEW_SRC_SYSTEM			0
#define SUSI_REAR_VIEW_SRC_EXTERNAL1		1
#define SUSI_REAR_VIEW_SRC_EXTERNAL2		2

#endif