#ifndef SUSI_VCIL_DEF_H
#define SUSI_VCIL_DEF_H

struct VCIL_MODULE_CONTROL
{
	bool CAN;
	bool J1708;
	bool J1939;
	bool OBD2;
	bool J1587;
};
typedef VCIL_MODULE_CONTROL* PVCIL_MODULE_CONTROL;

enum VCIL_CAN_CHANNEL_MODE
{
	VCIL_MODE_CAN                 = 0x00,
	VCIL_MODE_CAN_WITH_MASK,
	VCIL_MODE_J1939,
	VCIL_MODE_J1939_WITH_FILTER,
	VCIL_MODE_OBD2,
	VCIL_MODE_OBD2_WITH_FILTER
};
typedef VCIL_CAN_CHANNEL_MODE* PVCIL_CAN_CHANNEL_MODE;

enum VCIL_J1708_CHANNEL_MODE
{
	VCIL_MODE_J1708               = 0x00,
	VCIL_MODE_J1587
};
typedef VCIL_J1708_CHANNEL_MODE* PVCIL_J1708_CHANNEL_MODE;

#endif