#ifndef _SUSI_IMC_CORE_FUNCTION_API_H
#define _SUSI_IMC_CORE_FUNCTION_API_H

#include "SUSI_IMC_Types.h"


DLLAPI USHORT SUSI_IMC_CORE_Init();
DLLAPI USHORT SUSI_IMC_CORE_DeInit();
DLLAPI USHORT SUSI_IMC_CORE_Available();
DLLAPI USHORT SUSI_IMC_CORE_GetLibVersion( OUT BYTE version[18] );
DLLAPI USHORT SUSI_IMC_CORE_GetPlatformName(PIMC_CORE_GETPLATFORMNAME parm);
DLLAPI USHORT SUSI_IMC_CORE_AccessBootCounter(PIMC_CORE_ACCESS_BOOTCOUNTER parm);
DLLAPI USHORT SUSI_IMC_CORE_SoftReset(void);
DLLAPI USHORT SUSI_IMC_CORE_HardReset(void);
DLLAPI USHORT SUSI_IMC_CORE_Reset(void);
DLLAPI USHORT SUSI_IMC_CORE_GetImageinfo(PIMC_IMGINFO pInfo);
DLLAPI USHORT SUSI_IMC_CORE_RegistrySave(void);
DLLAPI USHORT SUSI_IMC_CORE_RegistryClean(void);

#endif