#ifndef _SUSI_IMC_IIC_API_H
#define _SUSI_IMC_IIC_API_H

#include "SUSI_IMC_IIC_Def.h"

DLLAPI USHORT SUSI_IMC_IIC_GetLibVersion( OUT BYTE version[18] );

DLLAPI USHORT SUSI_IMC_IIC_Available(void);
DLLAPI USHORT SUSI_IMC_IIC_Read(PIMC_IIC_READ parm);
DLLAPI USHORT SUSI_IMC_IIC_Write(PIMC_IIC_WRITE parm);
DLLAPI USHORT SUSI_IMC_IIC_WriteReadCombine(PIMC_IIC_WRITE_READ_COMBINE parm);

#endif