#ifndef SUSI_IMC_GSENSOR_API_H
#define SUSI_IMC_GSENSOR_API_H

#include "SUSI_IMC_Types.h"

DLLAPI USHORT SUSI_IMC_GSENSOR_Initialize(IN BYTE byPortNo);
DLLAPI USHORT SUSI_IMC_GSENSOR_Deinitialize(void);
DLLAPI USHORT SUSI_IMC_GSENSOR_GetLibVersion( OUT BYTE version[18] );
DLLAPI USHORT SUSI_IMC_GSENSOR_GetData(OUT PIMC_GSENSOR_DATA data);
DLLAPI USHORT SUSI_IMC_GSENSOR_GetResolution(OUT IMC_GSENSOR_RES *res);
DLLAPI USHORT SUSI_IMC_GSENSOR_SetResolution(IN IMC_GSENSOR_RES res);
DLLAPI USHORT SUSI_IMC_GSENSOR_AlarmEnabled(bool bActive);
DLLAPI USHORT SUSI_IMC_GSENSOR_SetAlarmEvent(void* hEvent);
DLLAPI USHORT SUSI_IMC_GSENSOR_GetAlarmData(OUT PIMC_GSENSOR_DATA data);
DLLAPI USHORT SUSI_IMC_GSENSOR_GetAlarmThreshold(OUT int *mg);
DLLAPI USHORT SUSI_IMC_GSENSOR_SetAlarmThreshold(IN int mg);
DLLAPI USHORT SUSI_IMC_GSENSOR_GetWakeupThreshold(OUT int *mg);
DLLAPI USHORT SUSI_IMC_GSENSOR_SetWakeupThreshold(IN int mg);

#endif